[package]
name = "rusterizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
array2d = "0.2.1"
tobj = "3.2.3"
png = "0.17.7"