[package]
name = "rusterizer"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.3.6"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tobj = "3.2.3"
png = "0.17.5"